version: '2.4'

services:

  browser_webrtc:
    image: browser-full-webrtc
    build:
      context: ./browser
      args:
        CHROMIUM_VERSION: "65.0.3325.181-0ubuntu0.16.04.1"
    ports:
      - 6789:6789
    environment:
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=760
      - SCREEN_DEPTH=16
      - VNC_PASS=test
    cap_add:
      - ALL
    tmpfs:
      - /tmp
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0


  html:
    build: ./html
    ports:
      - 8080:80
    depends_on:
      - signaling
    volumes:
      - ./html/:/usr/share/nginx/html/
  signaling:
    build: ./signaling
    ports:
      - 8443:8443
