[package]
name = "gst-rust"
version = "0.1.0"
authors = ["maxmcd <max.t.mcdonnell@gmail.com>"]

[dependencies]
clap = "2.31.2"
failure = "0.1.1"
glib = "0.6"
gstreamer = "0.12"
gstreamer-sdp = "0.12"
gstreamer-webrtc = "0.12"
lazy_static = "1.0"
rand = "0.5"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.19"
websocket = "0.20.2"
